/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-newspaper' : '&#x21;',
			'icon-home' : '&#x22;',
			'icon-picture' : '&#x23;',
			'icon-camera' : '&#x24;',
			'icon-play' : '&#x25;',
			'icon-camera-2' : '&#x26;',
			'icon-pencil' : '&#x27;',
			'icon-microphone' : '&#x28;',
			'icon-announcement' : '&#x29;',
			'icon-book' : '&#x2a;',
			'icon-license' : '&#x2b;',
			'icon-support' : '&#x2c;',
			'icon-cart' : '&#x2d;',
			'icon-mail' : '&#x2e;',
			'icon-location' : '&#x2f;',
			'icon-phone' : '&#x30;',
			'icon-mouse' : '&#x31;',
			'icon-printer' : '&#x32;',
			'icon-calendar' : '&#x33;',
			'icon-screen' : '&#x34;',
			'icon-comments' : '&#x35;',
			'icon-comments-2' : '&#x36;',
			'icon-users' : '&#x37;',
			'icon-search' : '&#x38;',
			'icon-unlocked' : '&#x39;',
			'icon-locked' : '&#x3a;',
			'icon-aid' : '&#x3b;',
			'icon-pie' : '&#x3c;',
			'icon-medal' : '&#x3d;',
			'icon-food' : '&#x3e;',
			'icon-coffee' : '&#x3f;',
			'icon-cup' : '&#x40;',
			'icon-lamp' : '&#x41;',
			'icon-airplane' : '&#x42;',
			'icon-cars' : '&#x43;',
			'icon-bus' : '&#x44;',
			'icon-truck' : '&#x45;',
			'icon-puzzle' : '&#x46;',
			'icon-accessibility' : '&#x47;',
			'icon-basketball' : '&#x48;',
			'icon-baseball' : '&#x49;',
			'icon-football' : '&#x4a;',
			'icon-soccer' : '&#x4b;',
			'icon-hockey' : '&#x4c;',
			'icon-golf' : '&#x4d;',
			'icon-racing' : '&#x4e;',
			'icon-clipboard' : '&#x4f;',
			'icon-upload' : '&#x50;',
			'icon-download' : '&#x51;',
			'icon-bookmark' : '&#x52;',
			'icon-bed' : '&#x54;',
			'icon-woman' : '&#x53;',
			'icon-man' : '&#x55;',
			'icon-happy' : '&#x56;',
			'icon-smiley' : '&#x57;',
			'icon-neutral' : '&#x58;',
			'icon-sad' : '&#x59;',
			'icon-cancel' : '&#x5a;',
			'icon-checkmark' : '&#x5b;',
			'icon-info' : '&#x5c;',
			'icon-minus' : '&#x5d;',
			'icon-arrow-right' : '&#x5e;',
			'icon-arrow-down' : '&#x5f;',
			'icon-arrow-left' : '&#x60;',
			'icon-arrow-up' : '&#x61;',
			'icon-arrow' : '&#x62;',
			'icon-arrow-2' : '&#x63;',
			'icon-arrow-3' : '&#x64;',
			'icon-arrow-4' : '&#x65;',
			'icon-facebook' : '&#x66;',
			'icon-twitter' : '&#x67;',
			'icon-youtube' : '&#x68;',
			'icon-flickr' : '&#x6a;',
			'icon-google-plus' : '&#x6b;',
			'icon-linkedin' : '&#x6c;',
			'icon-file-pdf' : '&#x6d;',
			'icon-file-word' : '&#x6e;',
			'icon-file-excel' : '&#x6f;',
			'icon-file-powerpoint' : '&#x70;',
			'icon-file-zip' : '&#x71;',
			'icon-firefox' : '&#x72;',
			'icon-IE' : '&#x73;',
			'icon-opera' : '&#x74;',
			'icon-safari' : '&#x75;',
			'icon-chrome' : '&#x76;',
			'icon-headset' : '&#x77;',
			'icon-quote' : '&#x78;',
			'icon-quote-2' : '&#x79;',
			'icon-bike' : '&#x7a;',
			'icon-at' : '&#x7b;',
			'icon-left-quote' : '&#x7c;',
			'icon-right-quote' : '&#x7d;',
			'icon-wordpress' : '&#xe000;',
			'icon-mobile' : '&#xe001;',
			'icon-dot' : '&#xe002;',
			'icon-feed' : '&#xe003;',
			'icon-warning' : '&#xe004;',
			'icon-help' : '&#xe005;',
			'icon-globe' : '&#xe006;',
			'icon-plus' : '&#xe007;',
			'icon-link' : '&#xe008;',
			'icon-flag' : '&#xe009;',
			'icon-volume-medium' : '&#xe00a;',
			'icon-star' : '&#xe00b;',
			'icon-copy' : '&#xe00c;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c) {
			addIcon(el, icons[c[0]]);
		}
	}
};